export const Component = {
  Application: Symbol.for('Application'),
  LoggerInterface: Symbol.for('LoggerInterface'),
  ConfigInterface: Symbol.for('ConfigInterface'),
  DatabaseInterface: Symbol.for('DatabaseInterface'),
  UserServiceInterface: Symbol.for('UserServiceInterface'),
  UserModel: Symbol.for('UserModel'),
  MovieModel: Symbol.for('MovieModel'),
  MovieServiceInterface: Symbol.for('MovieServiceInterface'),
  CommentServiceInterface: Symbol.for('CommentServiceInterface'),
  CommentModel: Symbol.for('CommentModel'),
  ExceptionFilterInterface: Symbol.for('ExceptionFilterInterface'),
  FilmController: Symbol.for('MovieController'),
  UserController: Symbol.for('UserController'),
  CommentController: Symbol.for('CommentController'),
};
